version: "3"

networks:
  http_network:
    external: true
  mail_network:
    external: false

services:
  traefik:
    image: traefik:1.5-alpine
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:mail.{{ DOMAIN }}
      - traefik.backend.port=8080
      - traefik.docker.network=http_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker/traefik/traefik.toml:/traefik.toml:ro
      - /mnt/docker/traefik/acme:/etc/traefik/acme
    networks:
      - http_network

  mailserver:
    image: hardware/mailserver:1.1-stable
    container_name: mailserver
    restart: unless-stopped
    domainname: {{ DOMAIN }}                  # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: mail
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:spam.{{ DOMAIN }}
      - traefik.backend.port=11334
      - traefik.docker.network=http_network
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS={{ DB_PASS }}                   # MariaDB database password (required)
      - RSPAMD_PASSWORD={{ RSPAMD_PASSWORD }}  # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...      # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true               # Disable greylisting policy
    # - DISABLE_RATELIMITING=true              # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - /mnt/docker/mail:/var/mail
    depends_on:
      - mariadb
      - redis
    networks:
      - mail_network
      - http_network

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    restart: unless-stopped
    domainname: {{ DOMAIN }}
    hostname: mail
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:postfixadmin.{{ DOMAIN }}
      - traefik.backend.port=8888
      - traefik.docker.network=http_network
    environment:
      - DBPASS={{ DB_PASS }}
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.backend.port=8888
      - traefik.frontend.rule=Host:webmail.{{ DOMAIN }}
      - traefik.docker.network=http_network
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network

  # Authoritative DNS server (Optional)
  # https://github.com/hardware/nsd-dnssec
  # https://www.nlnetlabs.nl/projects/nsd/
  # Configuration : https://github.com/hardware/mailserver/wiki/NSD-initial-configuration
  # nsd:
  #   image: hardware/nsd-dnssec
  #   container_name: nsd
  #   restart: unless-stopped
  #   ports:
  #     - "53:53"
  #     - "53:53/udp"
  #   volumes:
  #     - /mnt/docker/nsd/conf:/etc/nsd
  #     - /mnt/docker/nsd/zones:/zones
  #Â     - /mnt/docker/nsd/db:/var/db/nsd

  # Database
  # https://github.com/docker-library/mariadb
  # https://mariadb.org/
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    restart: unless-stopped
    # Info : These variables are ignored when the volume already exists (if databases was created before).
    environment:
      - MYSQL_ROOT_PASSWORD={{ ROOT_PASS }}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD={{ DB_PASS }}
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
    networks:
      - mail_network

  # Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:4.0-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - /mnt/docker/redis/db:/data
    networks:
      - mail_network
